name: backnend-Pipline

on:
  push:
    branches:
      - main

jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm i
      - name: run unit test
        run: npm run test


  build-and-push:
    runs-on: ubuntu-latest
    needs: Unit_test
    steps:
      
      - name: Clone repo
        uses: actions/checkout@v6

      - name: build docker image
        run: docker build -t chouchenechadha/api-session14 .

       
      - name: checkout image
        run: docker image

