name: backnend-Pipline

on:
  push:
    branches:
      - main

jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm i
      - name: run unit test
        run: npm run test

