name: backnend-Pipline

on:
  push:
    branches:
      - main

jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm i
      - name: run unit test
        run: npm run test


  build-and-push:
    runs-on: ubuntu-latest
    needs: Unit_test
    steps:
      
      - name: Clone repo
        uses: actions/checkout@v6

      - name: build docker image
        run: docker build -t chouchenechadha/api-session14 .
      

      - name: tag docker image
        run: docker tag chouchenechadha/api-session14 chouchenechadha/api-session14:v2

       
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: push image to dockerhub
        run: docker push chouchenechadha/api-session14

      - name: push image to dockerhub
        run: docker push chouchenechadha/api-session14:v2


  deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      
      - name: cnct via ssh and deplyment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
         
          script: |
            cd /home/user/devops14
            sudo docker compose down Backend
            sudo docker compose pull Backend
            sudo docker compose up -d --force-recreate
            

     
          